import path from 'node:path'
import { readFile, writeFile } from 'node:fs/promises'
import { STAGE, hashFile, recordFile, type Feature, type RunContext } from '@battlestack/core'
import { emitTemplate, emitTemplateUpdate } from '../utils/emit-template.js'
import { patchNuxtConfig } from '../utils/nuxt-config.js'

/**
 * Battlestack Design System Nuxt. Nuxt UI is the component library; this feature only
 * themes it — there is deliberately no component package to install.
 *
 * What it wires:
 *
 * - `extends: ['@battlestack/theme']` — the theme layer (fonts, `<BsLogo>`, assets).
 * - Two `@import`s appended to `app/assets/css/main.css`, in this order after
 *   `@import "@nuxt/ui"`: the layer's `tokens.css` (`@theme` ramps + `--ui-*` values,
 *   which must compile inside the project's Tailwind root — a layer cannot load them),
 *   then the project-owned `brand.css`.
 * - The semantic alias map in `app/app.config.ts`: `primary: 'brand'`,
 *   `secondary: 'lilac'`, `neutral: 'stone'`. Only the scaffold defaults are rewritten;
 *   a value the project changed stays untouched on `pull`.
 *
 * `requires` rather than `after`: without `nuxt4:nuxt-ui` there is no `main.css`, no
 * `app.config.ts` and nothing that reads a `--ui-*` variable — a theme for a component
 * library that isn't there is meaningless.
 */
export const battlestackThemeFeature: Feature = {
    id: 'nuxt4:battlestack-theme',
    version: '1.0.0',
    label: 'Battlestack theme (design system on Nuxt UI)',
    description: 'Battlestack tokens + brand for Nuxt UI, as a Nuxt layer.',
    frameworks: ['nuxt4'],
    stage: STAGE.STYLING,
    requires: ['nuxt4:nuxt-ui'],

    collectDeps() {
        return { prod: ['@battlestack/theme'] }
    },

    // The design-system instruction file is regenerated by `pull` like any other doc.
    // Only the brand stylesheet is the project's to edit.
    structuralFiles() {
        return ['app/assets/css/brand.css']
    },

    collectDocs() {
        return [
            {
                heading: 'Battlestack design system',
                body: [
                    '`DESIGN_SYSTEM.md` in the repo root is the authority for anything that renders. Read it before building or changing UI; this section is only the map.',
                    '',
                    '**Nuxt UI is the component library.** Every screen is composed from `U*` components (https://ui.nuxt.com/docs/components); this project does not build custom UI components. The order when something seems missing: existing component → composition (`UCard + UBadge + UButton`) → component props → `ui`/slot-class configuration → `app.config.ts` defaults → raise it as a design-system gap. Never a local lookalike.',
                    '',
                    'The design system itself is only a theme, delivered by the `@battlestack/theme` Nuxt layer:',
                    '',
                    '- `tokens.css` — Tailwind `@theme` ramps (brand / lilac / warm-stone) and the `--ui-*` values for light and dark, imported in `app/assets/css/main.css` after `@import "@nuxt/ui"`.',
                    '- the semantic alias map in `app/app.config.ts` (`ui.colors`: `primary: \'brand\'`, `secondary: \'lilac\'`, `neutral: \'stone\'`).',
                    '- `<BsLogo>` — the Battlestack lockup, the only component the layer ships (brand, not UI).',
                    '',
                    'Branding lives in tokens, only in tokens. This project\'s own overrides go in `app/assets/css/brand.css`, which is yours to edit and which `battlestack pull` never touches. Re-value existing `--ui-*` names there (both `:root` and `.dark`); never invent a name — nothing reads an invented name.',
                    '',
                    'In screens, use the semantic utilities Nuxt UI generates from the theme — `text-muted`, `bg-elevated`, `border-default`, `text-primary`, `rounded-md` — never raw hex, arbitrary px, or Tailwind palette classes (`text-blue-600`) when a semantic name exists.',
                ].join('\n'),
                targets: ['readme', 'agents'] as const satisfies Array<'readme' | 'agents'>,
            },
        ]
    },

    async execute(ctx) {
        await emitTemplate(ctx, 'nuxt4:battlestack-theme', import.meta.url, 'battlestack-theme')
        await wireTheme(ctx)
    },

    async update(ctx, prev) {
        const result = await emitTemplateUpdate(ctx, 'nuxt4:battlestack-theme', import.meta.url, 'battlestack-theme', prev)
        await wireTheme(ctx)
        return result
    },
}

async function wireTheme(ctx: RunContext): Promise<void> {
    await patchNuxtConfig(ctx.projectDir, (c) => {
        c.addExtends('@battlestack/theme')
    })
    await importThemeCss(ctx)
    await applyColorAliases(ctx)
}

/**
 * Appends the theme imports to `nuxt4:nuxt-ui`'s `main.css`. String-patched rather than
 * template-owned: two features owning one file would fight on every `pull`, and the CSS
 * has to live in this exact file — `@theme` only takes effect inside the stylesheet that
 * imports `tailwindcss`. Idempotent: each line is added once, order fixed by insertion.
 */
async function importThemeCss(ctx: RunContext): Promise<void> {
    const rel = 'app/assets/css/main.css'
    const cssPath = path.join(ctx.projectDir, rel)
    const original = await readFile(cssPath, 'utf8')
    let css = original
    for (const line of ['@import "@battlestack/theme/tokens.css";', '@import "./brand.css";']) {
        if (css.includes(line)) continue
        // After the last existing @import, never at EOF: a project may have appended its
        // own rules to main.css, and CSS rejects an @import that follows a rule.
        const lines = css.split('\n')
        // The anchor scan runs over a comment-blanked copy (same line numbering): an
        // @import inside `/* … */` must not be picked, or the theme imports get spliced
        // into the comment and silently never apply.
        const scannable = css
            .replace(/\/\*[\s\S]*?(?:\*\/|$)/g, (m) => m.replace(/[^\n]/g, ' '))
            .split('\n')
        const lastImport = scannable.reduce((last, l, i) => (l.trimStart().startsWith('@import') ? i : last), -1)
        lines.splice(lastImport + 1, 0, line)
        css = lines.join('\n')
    }
    if (css !== original) {
        await writeFile(cssPath, css, 'utf8')
        await rebaseline(ctx, rel)
    }
}

/**
 * Points the semantic aliases at the theme's ramps. Only the scaffold defaults
 * (`blue`/`purple`/`zinc`) are rewritten; any other value is a deliberate project
 * decision that a `pull` must not undo.
 *
 * Exported for `nuxt4:landing-shell`: `battlestack add nuxt4:landing-shell` re-emits
 * `app/app.config.ts` with the scaffold defaults, and only the added feature's
 * `execute()` runs — so it re-applies the aliases itself when the theme is enabled.
 */
export async function applyColorAliases(ctx: RunContext): Promise<void> {
    const rel = 'app/app.config.ts'
    const configPath = path.join(ctx.projectDir, rel)
    const source = await readFile(configPath, 'utf8')
    const patched = source
        .replace(/(primary:\s*)(['"])blue\2/, "$1'brand'")
        .replace(/(secondary:\s*)(['"])purple\2/, "$1'lilac'")
        .replace(/(neutral:\s*)(['"])zinc\2/, "$1'stone'")
    if (patched !== source) {
        await writeFile(configPath, patched, 'utf8')
        await rebaseline(ctx, rel)
    }
}

/**
 * The theme string-patches files that other features emitted and recorded
 * (`nuxt4:nuxt-ui` records both paths; `nuxt4:landing-shell` also records
 * `app/app.config.ts`). Every feature tracking the file gets its baseline moved to
 * the patched bytes — otherwise the recorded hash never matches disk again, and every
 * `pull` stages a conflict and every `doctor` reports drift, permanently.
 */
async function rebaseline(ctx: RunContext, rel: string): Promise<void> {
    const hash = await hashFile(path.join(ctx.projectDir, rel))
    // Recorded rels are platform-separated (`path.join` in the emit path), so on
    // Windows the maps hold `app\...` keys — compare separator-insensitively and
    // re-record under the exact key each map already uses.
    const posix = rel.replaceAll(path.sep, '/')
    for (const key of Object.keys(ctx.state)) {
        if (!key.startsWith('files:')) continue
        const map = ctx.state[key] as Record<string, string>
        for (const tracked of Object.keys(map)) {
            if (tracked.replaceAll(path.sep, '/') === posix) {
                recordFile(ctx, key.slice('files:'.length), tracked, hash)
            }
        }
    }
}
