import { STAGE, type Feature, type RunContext } from '@battlestack/core'
import { emitTemplate, emitTemplateUpdate } from '../utils/emit-template.js'
import { patchNuxtConfig } from '../utils/nuxt-config.js'

/**
 * SevenLab design system. Extends the `@sevenlab/ui-default` Nuxt layer and wires the
 * project's own `app/assets/css/brand.css`.
 *
 * The component library is **not** emitted as source. It arrives as a versioned package,
 * so a fix in `BsButton` reaches every project through a version bump instead of being
 * hand-carried into eight divergent copies. The only file this feature writes into the
 * app is the brand stylesheet, which the project owns.
 */
export const sevenlabUiFeature: Feature = {
    id: 'nuxt4:sevenlab-ui',
    version: '1.0.0',
    label: 'SevenLab UI (design system + default theme)',
    description: 'Bs* component library + default token theme, as a Nuxt layer.',
    frameworks: ['nuxt4'],
    stage: STAGE.STYLING,
    // The theme layer's `styles/bridge.css` maps our semantic tokens onto Nuxt UI's
    // `--ui-*` variables, so it has to be the last word on styling. `after` rather than
    // `requires`: the layer stands on its own without `@nuxt/ui` (the bridge then simply
    // maps variables nothing reads), so a project that drops Nuxt UI still works.
    after: ['nuxt4:nuxt-ui'],

    collectDeps() {
        // `@sevenlab/ui-default` depends on `@sevenlab/ui`, so the component layer arrives
        // transitively. Declaring both would pin two versions that must be moved in lockstep.
        return { prod: ['@sevenlab/ui-default'] }
    },

    // The design system's own instruction file is regenerated by `pull` like any other doc.
    // Only the brand stylesheet is the project's to edit.
    structuralFiles() {
        return ['app/assets/css/brand.css']
    },

    collectDocs() {
        return [
            {
                heading: 'SevenLab UI design system',
                body: [
                    '`DESIGN_SYSTEM.md` in the repo root is the authority for anything that renders. Read it before building or changing UI; this section is only the map.',
                    '',
                    'Three layers, each a Nuxt layer extending the one before it:',
                    '',
                    '- `@sevenlab/ui` — the components (`<BsButton>`, `<BsDataTable>`, `<BsAppShell>`, …). Structure, behaviour and states. It defines no colour, size or radius of its own.',
                    '- `@sevenlab/ui-default` — the token values for light and dark, plus the Nuxt UI bridge that puts `UCard`/`UButton` markup on the same tokens. This is what `nuxt.config.ts#extends` points at; the component layer comes with it.',
                    '- `@sevenlab/ui-<client>` — a per-client theme extending the default one. It overrides token *values* and nothing else.',
                    '',
                    'Branding lives in tokens, only in tokens. This project\'s own overrides go in `app/assets/css/brand.css`, which is yours to edit and which `battlestack pull` never touches. Re-value existing token names there (`--primary`, `--font-sans`, `--card-radius`); never invent a name, because every component is written against the name set that `@sevenlab/ui-default` publishes and a name it does not know resolves to nothing.',
                    '',
                    'Changing a component to achieve branding is the one thing that is always wrong. Both packages are installed from npm, so an edit inside `node_modules` is gone on the next install; a genuine gap is a design-system change, raised there and delivered by a version bump.',
                ].join('\n'),
                targets: ['readme', 'agents'] as const satisfies Array<'readme' | 'agents'>,
            },
        ]
    },

    async execute(ctx) {
        await emitTemplate(ctx, 'nuxt4:sevenlab-ui', import.meta.url, 'sevenlab-ui')
        await configureNuxtConfig(ctx)
    },

    async update(ctx, prev) {
        const result = await emitTemplateUpdate(ctx, 'nuxt4:sevenlab-ui', import.meta.url, 'sevenlab-ui', prev)
        await configureNuxtConfig(ctx)
        return result
    },
}

async function configureNuxtConfig(ctx: RunContext): Promise<void> {
    await patchNuxtConfig(ctx.projectDir, (c) => {
        c.addExtends('@sevenlab/ui-default')
        // After `nuxt4:nuxt-ui`'s `main.css`, so a project override outranks both Tailwind's
        // theme and the design system's own token values. Both are appends, and this feature
        // runs after `nuxt4:nuxt-ui`, so the order holds on scaffold and on every pull.
        c.addCss('~/assets/css/brand.css')
    })
}
