import type { BattlestackPluginContext } from '@battlestack/core'

/**
 * No template hardcodes a private deploy feature. A private plugin adds one via `extendTemplate`.
 *
 * `nuxt4:battlestack-theme` is optional and default-OFF in all three templates.
 * `@battlestack/theme` is not on a registry yet and this preset is published, so any
 * path that pulls the dependency in by default — required *or* default-on — makes
 * `battlestack create` fail at install time for everyone accepting the defaults.
 * Opting in is a deliberate act by someone who can point the dependency at a local
 * checkout. The package is publishable as of 1.2.0 and its first publish is manual;
 * flip to required once it is on npm: it is the house standard, so required is the
 * right default then — the only reason it is not is distribution, not design.
 */
export function registerNuxtTemplates(battlestack: BattlestackPluginContext): void {
    battlestack.addTemplate({
        id: 'nuxt4-ai',
        label: 'Nuxt (AI app)',
        description: 'Full stack + Mastra agents + WebSocket streaming chat + Docker. RAG opt-in.',
        framework: 'nuxt4',
        requiredFeatures: [
            'nuxt4:scaffold',
            'nuxt4:gitignore',
            'shared:formatting',
            'shared:package-policy',
            'nuxt4:naming',
            'nuxt4:essentials',
            'nuxt4:nuxt-ui',
            'nuxt4:landing-shell',
            'nuxt4:vitest',
            'nuxt4:i18n',
            'nuxt4:database',
            'nuxt4:auth',
            'nuxt4:dashboard-shell',
            'nuxt4:mastra',
            'nuxt4:chat',
            'nuxt4:health',
            'nuxt4:pinia',
            'shared:docker',
            'shared:github',
            'shared:security',
            'shared:ai-tool-config',
            'nuxt4:docs',
            'shared:env',
            'shared:install',
            'nuxt4:finalize',
        ],
        optionalFeatures: [
            'nuxt4:battlestack-theme',
            'nuxt4:audit-log',
            'nuxt4:user-admin',
            'nuxt4:auth-passkeys',
            'nuxt4:auth-recovery',
            'nuxt4:auth-2fa',
            'nuxt4:oauth',
            'nuxt4:storage',
            'nuxt4:redis',
            'nuxt4:rag',
            'nuxt4:prompts',
            'nuxt4:pwa',
            'shared:ci',
            'shared:playwright',
        ],
        defaultEnabledOptional: [
            'nuxt4:pwa',
            'shared:ci',
            'nuxt4:audit-log',
            'nuxt4:user-admin',
            'nuxt4:auth-recovery',
            'nuxt4:auth-2fa',
            'nuxt4:auth-passkeys',
            'nuxt4:storage',
            'nuxt4:rag',
            'nuxt4:prompts',
            'shared:playwright',
            // `nuxt4:redis` is offered but not default-on.
        ],
    })

    battlestack.addTemplate({
        id: 'nuxt4-fullstack',
        label: 'Nuxt (full stack)',
        description: 'Nuxt + UI + i18n + Postgres + Drizzle + custom auth + Mastra + Docker.',
        framework: 'nuxt4',
        requiredFeatures: [
            'nuxt4:scaffold',
            'nuxt4:gitignore',
            'shared:formatting',
            'shared:package-policy',
            'nuxt4:naming',
            'nuxt4:essentials',
            'nuxt4:nuxt-ui',
            'nuxt4:landing-shell',
            'nuxt4:vitest',
            'nuxt4:i18n',
            'nuxt4:database',
            'nuxt4:auth',
            'nuxt4:dashboard-shell',
            'nuxt4:mastra',
            'nuxt4:health',
            'nuxt4:pinia',
            'shared:docker',
            'shared:github',
            'shared:security',
            'shared:ai-tool-config',
            'nuxt4:docs',
            'shared:env',
            'shared:install',
            'nuxt4:finalize',
        ],
        optionalFeatures: [
            'nuxt4:battlestack-theme',
            'nuxt4:audit-log',
            'nuxt4:user-admin',
            'nuxt4:auth-passkeys',
            'nuxt4:auth-recovery',
            'nuxt4:auth-2fa',
            'nuxt4:oauth',
            'nuxt4:storage',
            'nuxt4:chat',
            'nuxt4:redis',
            'nuxt4:rag',
            'nuxt4:prompts',
            'nuxt4:pwa',
            'shared:ci',
            'shared:playwright',
        ],
        defaultEnabledOptional: [
            'nuxt4:pwa',
            'shared:ci',
            'nuxt4:audit-log',
            'nuxt4:user-admin',
            'nuxt4:auth-recovery',
            'nuxt4:auth-2fa',
            'nuxt4:auth-passkeys',
            'nuxt4:storage',
            'shared:playwright',
            // `nuxt4:redis` is offered but not default-on.
        ],
    })

    battlestack.addTemplate({
        id: 'nuxt4-minimal',
        label: 'Nuxt (minimal)',
        description: 'Nuxt 4 + UI v4 + Tailwind v4 only. No backend, no auth.',
        framework: 'nuxt4',
        requiredFeatures: [
            'nuxt4:scaffold',
            'nuxt4:gitignore',
            'shared:formatting',
            'shared:package-policy',
            'nuxt4:naming',
            'nuxt4:essentials',
            'nuxt4:nuxt-ui',
            'nuxt4:vitest',
            'nuxt4:i18n',
            'nuxt4:health',
            'nuxt4:pinia',
            'shared:docker',
            'shared:github',
            'shared:security',
            'shared:ai-tool-config',
            'nuxt4:docs',
            'shared:env',
            'shared:install',
            'nuxt4:finalize',
        ],
        optionalFeatures: [
            'nuxt4:battlestack-theme',
            'nuxt4:landing-shell',
            'nuxt4:pwa',
            'shared:ci',
            'shared:playwright',
        ],
        defaultEnabledOptional: [
            'nuxt4:landing-shell',
            'nuxt4:pwa',
            'shared:ci',
            'shared:playwright',
        ],
    })
}
