<template>
    <div class="space-y-4">
        <h1 class="text-2xl font-semibold">{{ projectName }}</h1>
        <p class="text-sm text-muted">
            Generated by <code>battlestack</code>. Run <code>battlestack</code> from this
            directory to see the available task commands.
        </p>
    </div>
</template>

<script setup lang="ts">
const projectName = useRuntimeConfig().public?.appName ?? 'Battlestack project'
</script>
